### ISSUE TITLE
Saving the Tournament asks for Web Services

### ISSUE THREAD

**Issue by SpaceDivider** [MrHuds0n/golden#26] opened 2017-05-15 20:48 UTC
The first time a tournament is saved the pop-up appears that "using web services will upload your tournament data to an external website".
On canceling, the results are still saved to file which may not be apparent.
Also saving (the icon hints at 'saving to disk') does not directly relate with using the web services.

I would propose a different wording along the lines of "Your Results are saved. Do you want to enable Web Services?"

Edit:
Generally a visual cue that the save was successful would be nice.

**Comment by zanlib0** [comment] 2017-05-16 17:47
Good point, will be added.

**Comment by zanlib0** [comment] 2017-05-17 20:35
In hindsight (because it's best to come up with the correct idea *after* you've implemented the wrong one) it would be significantly more user-friendly if there was a web services checkbox when creating a tournament.

Also the issue is pretty much fixed with the next commit as I've added a toast component (because alerts are bad UX) to the UI which will likely help with everything.

**Closed as completed** 2017-05-17 20:52 UTC
Labels: feature request
